version: '3.9'

services:
  web:
    build: 
      context: .
      dockerfile: DockerFile
    ports:
      - 5063:80
    environment:
      - IPFS_PATH=/opt/.csipfs
    volumes:
      - ipfsVolume:/opt/.csipfs

volumes:
  ipfsVolume: